### ISSUE TITLE
Page Layout (Header/Main/Footer)

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/guess-the-movie#15]
As a user I would like to experience the following:

- an introduction to the "Guess the Movie" game 
- instructions on how to play
- access to settings
- information on Bitwise Workforce Training

So that I can play a non-competitive API based game made by the apprentices at Bitwise Workforce Training/Alphaworks.

**Assets**
- Wireframe

**Comment by ProjectErostribe** [comment]
I would like to explore the idea of incorporating animations in the instructions on the Home Screen in order to make the experience more interactive.

I would also like to state that this could touch on the idea of settings being accessible on the Home Screen as well, so I would like to include whoever has the settings task.

**Comment by ProjectErostribe** [comment]
Here is what the project looks like at the moment.

![Screenshot from 2022-02-10 14-17-18](https://user-images.githubusercontent.com/78198093/153511529-64f3409a-ed55-4fdb-addc-bb75846317de.png)

Here are things I suggest should be done to make the page look and feel more like a game:
- Add the styling so it looks similar to a movie film strip and the words are where they need to be on the page.
- Add the links on the header
- Team name fix
- Link to [Bitwise Workforce Training website](https://bitwiseindustries.com/services/workforce-training/about/)
- Link to [Bitwise Workforce Twitter](https://twitter.com/BitwiseTraining)
- Link to [Project GitHub Repo](https://github.com/luceroweb/guess-the-movie)
