### ISSUE TITLE
Game Over: image load delay bug

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#154]
Date Seen
4/7/22 11:20am

Versions
Linux
Chrome & Android
[develop](https://github.com/luceroweb/guess-the-movie/tree/develop)

**Bug Description**
There is a noticeable delay when the `GameOver` scene loads.The drive-in foreground and starry sky background images will load after the Game Over Screen.  The delay is most pronounced in the emulator, but it also occurs slightly in the browser too.

**Steps to Reproduce**
1. Start Game
2. Answer Question incorrectly
3. Observe carefully as `GameOver` scene first loads.  There is a momentary delay after the "Game Over" screen loads and when the foreground and background drive-in images load on the screen. 

**Actual Behavior**
The div with the Game Over text and the 'Start Over' ticket load before the foreground and background drive-in and starry sky images load.

**Expected Behavior**
The whole scene should load at the same time.  

Troubleshooting/Testing Steps Attempted
N/A

**Workaround**
none

**Comment by alberme** [comment]
When we were googling around, we read that Expo does not bundle assets such as images directly into the app. Rather they are downloaded either from the localhost server in development or from Expo's CDN's (content delivery networks) in production.

https://docs.expo.dev/guides/how-expo-works/#metro-bundler
> When you include an image in your app, you will use syntax like <Image source={require('./assets/example.png')} />, and unless you have already cached that asset the app the import will be resolved to a URL that points to your Metro server.

https://docs.expo.dev/guides/preloading-and-caching-assets/#publishing-assets
> When you publish your project, it will upload your assets to the CDN so that they may be fetched when users run your app. However, in order for assets to be uploaded to the CDN they must be explicitly required somewhere in your application's code. Conditionally requiring assets will result in the bundler being unable to detect them and therefore they will not be uploaded when you publish your project.

Initially we thought this was the issue. That the same images were always getting fetched every time the GameOver scene gets rendered (and this applies to all the other scenes that use different images such as Main, Question, HowToPlay)

The useCachedAssets hook I wrote fixed the issue for web and iOS. I used this template as a guide
https://github.com/expo/expo/blob/345a2db8b6f1c4fe23e2f2773ff4226566665f35/templates/expo-template-tabs/hooks/useCachedResources.ts#L6

However it did not work for Android.
We tried
* Adding the Images folder path to assetBundlePatterns in app.json
* Using packages such as expo-fast-image, react-native-fast-image
* Passing the exact uri's to the images in local storage to the Image elements
* Setting the fadeDuration prop on Image to 0
* Optimizing the images using `npx expo-optimize`
* Wrapping the images within a View and experiment with the [elevation](https://reactnative.dev/docs/view-style-props#elevation-android) and zIndex styles
* Commenting out other Views and styles not related to the background images to minimize the scope of the issue

The last fix we tried was pre-rendering the GameOver scene in *Nav.js*. We added a hide prop to GameOver that toggles a display css property to either none or flex. We can then let the GameOver component pre-render on app start but keep it hidden until the scene state is switched to GameOver. However, the scene either flickers or fades in slowly on the initial render but loads instantly on subsequent renders.

We believe it may have to do with the initial width calculations but because we spent alot of time on this issue, it may be time for someone else to digest our analysis and attempt a fix. Our branch name is [gsh-154-image-load-delay-bug](https://github.com/luceroweb/guess-the-movie/tree/gsh-154-image-load-delay-bug)
