### ISSUE TITLE
Fix 'postMessage'/'onPlayerReady' bug on CorrectAnswer Page

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#47]
![correctanswer2](https://user-images.githubusercontent.com/91571340/156465793-fe91ad25-08a3-4f13-b61f-4c29636c552e.png)

**Date Seen**
3/2/22 3pm

**Versions**
Linux Chrome Web Browser
[sr-44-screen-fix](https://github.com/luceroweb/guess-the-movie/tree/sr-44-screen-fix)

**Bug Description**
An error shows on the CorrectAnswer Scene regarding iframe, 'postMessage', and 'onPlayerReady'

**Steps to Reproduce**
1. Start the game
2. Answer a question correctly
3. Error shows in the web browser console on CorrectAnswer Scene.

**Actual Behavior**
After getting a Question right, on in the web browser, error shows in console on CorrectAnswer Scene.

**Expected Behavior**
There would be no error in the console.

**Troubleshooting/Testing Steps Attempted**
None so far

**Workaround**
None so far

**Comment by Hiwot-Beshe** [comment]
Our group tried to fix the error. The error came from react-native-youtube-iframe because of the iframe setup. 
We tried changing the “youtubePlayer” to “WebView”.

import{WebView} from "react-native-web-webview"
 <WebView
// mediaPlaybackRequiresUserAction={true}
// style={{ height:240, width:320,alignSelf:"center",alignContent:"center"}}
// javaScriptEnabled={true}
// // domStorageEnabled={true}
// source={{uri:`https://www.youtube.com/embed/${youTubeId}?rel=0` }}
// />


The WebView is working for web but not emulator. Emulator show undefine on getYouTubeId(movieId).then((res) => {
{
 useEffect(() => {
   getYouTubeId(movieId).then((res) => {
     setYouTubeId(res);
   });
 }, []);
}

**Comment by eyobel7k** [comment]
my team and I installed and tried different youtube packages, however the same error existed on the other packages. 

Similar packages used:
[react-native-youtube](https://www.npmjs.com/package/react-native-youtube)
[@ktree/react-native-youtube](https://www.npmjs.com/package/@ktree/react-native-youtube) and
[react-native-youtube-sdk](https://www.npmjs.com/package/react-native-youtube-sdk)

**Comment by garanico** [comment]
we also tried adding a check for window.reactNativeWebView in addition to the youtubeId.  This resulted in no errors, but that is because it was returning "false"
![reactNativeWebView](https://user-images.githubusercontent.com/82012415/158493184-b26468be-91f9-4d7e-8c18-faac2f90dbed.png)

**Comment by srosenberg74** [comment]
Found these two potential resources, but still haven't found solution:

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
https://imelgrat.me/javascript/youtube-iframe-api-javascript/
